version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'bitnami:/bitnami'
  joomla:
    image: 'bitnami/joomla:latest'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - 'bitnami:/bitnami'
    depends_on:
      - mariadb

volumes:
  bitnami:
    driver: local
